### ISSUE TITLE
使用多类型时候，会报数组下标越界，导致程序崩溃。

### ISSUE THREAD

**Issue by ITBOOSLI** [JunhuaLin/CommonAdapter#1]
验证方式：在DefaultViewBinderActivity的oncreate方法中添加一段更新数据并notifyDataSetChanged的代码。

 handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 2; i++) {
                    dataList.add(new GoodsShowBean());
                }

                dataList.add(new BigTitleBean("猜你喜欢"));
                for (int i = 0; i < 10; i++) {
                    dataList.add(new LikeBean());
                }
                multiTypeAdapter.notifyDataSetChanged();
            }
        },5000);

**Comment by JunhuaLin** [comment]
已修复，使用最新版
